---
- name: Deploy anarchy-k8s-config
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    anarchy_gitops_deploy_autonomous: true
    k8s_config:
      run_interval: 1h
    k8s_config_sources:
    - name: k8s_config_demo
      base_path: "{{ playbook_dir }}/k8s-config"
    set_k8s_cluster_info:
      env_level: dev

  pre_tasks:
  - name: Set facts about the cluster
    include_tasks:
      file: set-facts.yml

  roles:
  - role: k8s_config
